
const state = {
    AtomsData: [
        {
            nom: 'H',
            nomComplet: 'Hydrogène',
            nombreAtomique: 1,
            masseAtomique: 1.00797,
            rayonIonique: 0.208,
            rayonCovalent: 30,
            nombreDeMasse: 1,
            nombreDeNeutrons: 0,
            electronegativite: 2.1,
            energieIonisation: 1312.0,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 4.50711,
        },
        {
            nom: 'D',
            nomComplet: 'Deutérieum',
            nombreAtomique: 1,
            masseAtomique: 2.01410,
            rayonIonique: 0.208,
            rayonCovalent: 30,
            nombreDeMasse: 2,
            nombreDeNeutrons: 1,
            electronegativite: 2.1,
            energieIonisation: 1312.0,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 4.50711,
        },
        {
            nom: 'T',
            nomComplet: 'Tritium',
            nombreAtomique: 1,
            masseAtomique: 3.01605,
            rayonIonique: 0.208,
            rayonCovalent: 30,
            nombreDeMasse: 3,
            nombreDeNeutrons: 2,
            electronegativite: 2.1,
            energieIonisation: 1312.0,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 4.50711,
        },
        {
            nom: 'He',
            nomComplet: 'Hélium',
            nombreAtomique: 2,
            masseAtomique: 4.00260,
            rayonIonique: '--',
            rayonCovalent: 28,
            nombreDeMasse: 4,
            nombreDeNeutrons: 2,
            electronegativite: '--',
            energieIonisation: 2372.3,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 1.38375,
        },
        {
            nom: 'Li',
            nomComplet: 'Lithium',
            nombreAtomique: 3,
            masseAtomique: 6.941,
            rayonIonique: 0.068,
            rayonCovalent: 128,
            nombreDeMasse: 7,
            nombreDeNeutrons: 4,
            electronegativite: 1.0,
            energieIonisation: 520.2,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 164.1125,
        },
        {
            nom: 'Be',
            nomComplet: 'Béryllium',
            nombreAtomique: 4,
            masseAtomique: 9.01218,
            rayonIonique: 0.031,
            rayonCovalent: 96,
            nombreDeMasse: 9,
            nombreDeNeutrons: 5,
            electronegativite: 1.6,
            energieIonisation: 899.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 37.74,
        },
        {
            nom: 'B',
            nomComplet: 'Bore',
            nombreAtomique: 5,
            masseAtomique: 10.81,
            rayonIonique: '--',
            rayonCovalent: 84,
            nombreDeMasse: 11,
            nombreDeNeutrons: 6,
            electronegativite: 2.0,
            energieIonisation: 800.6,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 20.5,
        },
        {
            nom: 'C',
            nomComplet: 'Carbone',
            nombreAtomique: 6,
            masseAtomique: 12.011,
            rayonIonique: 0.260,
            rayonCovalent: 69,
            nombreDeMasse: 12,
            nombreDeNeutrons: 6,
            electronegativite: 2.5,
            energieIonisation: 1086.5,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 11.3,
        },
        {
            nom: 'C13',
            nomComplet: 'Carbone13',
            nombreAtomique: 6,
            masseAtomique: 13.00336,
            rayonIonique: 0.260,
            rayonCovalent: 69,
            nombreDeMasse: 13,
            nombreDeNeutrons: 7,
            electronegativite: 2.5,
            energieIonisation: 1086.5,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 11.3,
        },
        {
            nom: 'N',
            nomComplet: 'Azote',
            nombreAtomique: 7,
            masseAtomique: 14.0067,
            rayonIonique: 0.171,
            rayonCovalent: 71,
            nombreDeMasse: 14,
            nombreDeNeutrons: 7,
            electronegativite: 3.0,
            energieIonisation: 1402.3,
            electronsValence: 5,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 7.4,
        },
        {
            nom: 'O',
            nomComplet: 'Oxygène',
            nombreAtomique: 8,
            masseAtomique: 15.9994,
            rayonIonique: 0.140,
            rayonCovalent: 66,
            nombreDeMasse: 16,
            nombreDeNeutrons: 8,
            electronegativite: 3.5,
            energieIonisation: 1313.9,
            electronsValence: 6,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 5.3,
        },
        {
            nom: 'F',
            nomComplet: 'Fluor',
            nombreAtomique: 9,
            masseAtomique: 18.998403,
            rayonIonique: 0.136,
            rayonCovalent: 57,
            nombreDeMasse: 19,
            nombreDeNeutrons: 10,
            electronegativite: 4.0,
            energieIonisation: 1681.0,
            electronsValence: 7,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 3.74,
        },
        {
            nom: 'Ne',
            nomComplet: 'Néon',
            nombreAtomique: 10,
            masseAtomique: 20.179,
            rayonIonique: '--',
            rayonCovalent: 58,
            nombreDeMasse: 20,
            nombreDeNeutrons: 10,
            electronegativite: '--',
            energieIonisation: 2080.7,
            electronsValence: 8,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 2.66110,
        },
        {
            nom: 'Na',
            nomComplet: 'Sodium',
            nombreAtomique: 11,
            masseAtomique: 22.98977,
            rayonIonique: 0.095,
            rayonCovalent: 166,
            nombreDeMasse: 23,
            nombreDeNeutrons: 12,
            electronegativite: 0.9,
            energieIonisation: 495.8,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 162.7,
        },
        {
            nom: 'Mg',
            nomComplet: 'Magnésium',
            nombreAtomique: 12,
            masseAtomique: 24.305,
            rayonIonique: 0.065,
            rayonCovalent: 141,
            nombreDeMasse: 24,
            nombreDeNeutrons: 12,
            electronegativite: 1.3,
            energieIonisation: 737.7,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 71.2,
        },
        {
            nom: 'Al',
            nomComplet: 'Aluminium',
            nombreAtomique: 13,
            masseAtomique: 26.98154,
            rayonIonique: 0.050,
            rayonCovalent: 121,
            nombreDeMasse: 27,
            nombreDeNeutrons: 14,
            electronegativite: 1.6,
            energieIonisation: 577.5,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 57.8,
        },
        {
            nom: 'Si',
            nomComplet: 'Silicium',
            nombreAtomique: 14,
            masseAtomique: 28.0855,
            rayonIonique: 0.041,
            rayonCovalent: 111,
            nombreDeMasse: 28,
            nombreDeNeutrons: 14,
            electronegativite: 1.9,
            energieIonisation: 786.5,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 37.3,
        },
        {
            nom: 'P',
            nomComplet: 'Phosphore',
            nombreAtomique: 15,
            masseAtomique: 30.97376,
            rayonIonique: 0.212,
            rayonCovalent: 107,
            nombreDeMasse: 31,
            nombreDeNeutrons: 16,
            electronegativite: 2.2,
            energieIonisation: 1011.8,
            electronsValence: 5,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 25,
        },
        {
            nom: 'S',
            nomComplet: 'Soufre',
            nombreAtomique: 16,
            masseAtomique: 32.06,
            rayonIonique: 0.184,
            rayonCovalent: 105,
            nombreDeMasse: 32,
            nombreDeNeutrons: 16,
            electronegativite: 2.5,
            energieIonisation: 999.6,
            electronsValence: 6,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 19.4,
        },
        {
            nom: 'Cl',
            nomComplet: 'Chlore',
            nombreAtomique: 17,
            masseAtomique: 35.453,
            rayonIonique: 0.181,
            rayonCovalent: 102,
            nombreDeMasse: 35,
            nombreDeNeutrons: 18,
            electronegativite: 3.0,
            energieIonisation: 1251.2,
            electronsValence: 7,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 14.6,
        },
        {
            nom: 'Ar',
            nomComplet: 'Argon',
            nombreAtomique: 18,
            masseAtomique: 39.948,
            rayonIonique: '--',
            rayonCovalent: 106,
            nombreDeMasse: 40,
            nombreDeNeutrons: 22,
            electronegativite: '--',
            energieIonisation: 1520.6,
            electronsValence: 8,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 11.083,
        },
        {
            nom: 'K',
            nomComplet: 'Potassium',
            nombreAtomique: 19,
            masseAtomique: 39.0983,
            rayonIonique: 0.133,
            rayonCovalent: 203,
            nombreDeMasse: 39,
            nombreDeNeutrons: 20,
            electronegativite: 0.8,
            energieIonisation: 418.8,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 289.7,
        },
        {
            nom: 'Ca',
            nomComplet: 'Calcium',
            nombreAtomique: 20,
            masseAtomique: 40.08,
            rayonIonique: 0.099,
            rayonCovalent: 176,
            nombreDeMasse: 40,
            nombreDeNeutrons: 20,
            electronegativite: 1.3,
            energieIonisation: 589.8,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 160.8,
        },
        {
            nom: 'Sc',
            nomComplet: 'Scandium',
            nombreAtomique: 21,
            masseAtomique: 44.9559,
            rayonIonique: 0.081,
            rayonCovalent: 170,
            nombreDeMasse: 45,
            nombreDeNeutrons: 24,
            electronegativite: 1.4,
            energieIonisation: 633.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 97,
        },
        {
            nom: 'Ti',
            nomComplet: 'Titane',
            nombreAtomique: 22,
            masseAtomique: 47.90,
            rayonIonique: 0.068,
            rayonCovalent: 160,
            nombreDeMasse: 48,
            nombreDeNeutrons: 26,
            electronegativite: 1.5,
            energieIonisation: 	658.8,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 100,
        },
        {
            nom: 'V',
            nomComplet: 'Vanadium',
            nombreAtomique: 23,
            masseAtomique: 50.9415,
            rayonIonique: 0.052,
            rayonCovalent: 153,
            nombreDeMasse: 51,
            nombreDeNeutrons: 28,
            electronegativite: 1.6,
            energieIonisation: 650.9,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 87,
        },
        {
            nom: 'Cr',
            nomComplet: 'Chrome',
            nombreAtomique: 24,
            masseAtomique: 51.996,
            rayonIonique: 0.052,
            rayonCovalent: 139,
            nombreDeMasse: 52,
            nombreDeNeutrons: 28,
            electronegativite: 1.7,
            energieIonisation: 652.9,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 83,
        },
        {
            nom: 'Mn',
            nomComplet: 'Manganèse',
            nombreAtomique: 25,
            masseAtomique: 54.9380,
            rayonIonique: 0.046,
            rayonCovalent: 139,
            nombreDeMasse: 55,
            nombreDeNeutrons: 30,
            electronegativite: 1.6,
            energieIonisation: 717.3,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 68,
        },
        {
            nom: 'Fe',
            nomComplet: 'Fer',
            nombreAtomique: 26,
            masseAtomique: 55.847,
            rayonIonique: 0.064,
            rayonCovalent: 132,
            nombreDeMasse: 56,
            nombreDeNeutrons: 30,
            electronegativite: 1.8,
            energieIonisation: 762.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 62,
        },
        {
            nom: 'Co',
            nomComplet: 'Cobalt',
            nombreAtomique: 27,
            masseAtomique: 58.9332,
            rayonIonique: 0.074,
            rayonCovalent: 126,
            nombreDeMasse: 59,
            nombreDeNeutrons: 32,
            electronegativite: 1.9,
            energieIonisation: 760.4,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 55,
        },
        {
            nom: 'Ni',
            nomComplet: 'Nickel',
            nombreAtomique: 28,
            masseAtomique: 58.70,
            rayonIonique: 0.072,
            rayonCovalent: 124,
            nombreDeMasse: 58,
            nombreDeNeutrons: 30,
            electronegativite: 1.9,
            energieIonisation: 737.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 49,
        },
        {
            nom: 'Cu',
            nomComplet: 'Cuivre',
            nombreAtomique: 29,
            masseAtomique: 63.546,
            rayonIonique: 0.072,
            rayonCovalent: 132,
            nombreDeMasse: 63,
            nombreDeNeutrons: 34,
            electronegativite: 1.9,
            energieIonisation: 745.5,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 46.5,
        },
        {
            nom: 'Zn',
            nomComplet: 'Zinc',
            nombreAtomique: 30,
            masseAtomique: 65.38,
            rayonIonique: 0.074,
            rayonCovalent: 122,
            nombreDeMasse: 64,
            nombreDeNeutrons: 34,
            electronegativite: 1.7,
            energieIonisation: 906.4,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 38.67,
        },
        {
            nom: 'Ga',
            nomComplet: 'Gallium',
            nombreAtomique: 31,
            masseAtomique: 69.72,
            rayonIonique: 0.062,
            rayonCovalent: 122,
            nombreDeMasse: 69,
            nombreDeNeutrons: 38,
            electronegativite: 1.6,
            energieIonisation: 578.8,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 50,
        },
        {
            nom: 'Ge',
            nomComplet: 'Germanium',
            nombreAtomique: 32,
            masseAtomique: 72.59,
            rayonIonique: 0.053,
            rayonCovalent: 120,
            nombreDeMasse: 74,
            nombreDeNeutrons: 42,
            electronegativite: 2.0,
            energieIonisation: 762,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 40,
        },
        {
            nom: 'As',
            nomComplet: 'Arsenic',
            nombreAtomique: 33,
            masseAtomique: 74.9216,
            rayonIonique: 0.222,
            rayonCovalent: 119,
            nombreDeMasse: 75,
            nombreDeNeutrons: 42,
            electronegativite: 2.2,
            energieIonisation: 947.0,
            electronsValence: 5,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 30,
        },
        {
            nom: 'Se',
            nomComplet: 'Sélénium',
            nombreAtomique: 34,
            masseAtomique: 78.96,
            rayonIonique: 0.198,
            rayonCovalent: 120,
            nombreDeMasse: 80,
            nombreDeNeutrons: 46,
            electronegativite: 2.6,
            energieIonisation: 941.0,
            electronsValence: 6,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 28.9,
        },
        {
            nom: 'Br',
            nomComplet: 'Brome',
            nombreAtomique: 35,
            masseAtomique: 79.904,
            rayonIonique: 0.196,
            rayonCovalent: 120,
            nombreDeMasse: 79,
            nombreDeNeutrons: 44,
            electronegativite: 2.8,
            energieIonisation: 1139.9,
            electronsValence: 7,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 21,
        },
        {
            nom: 'Kr',
            nomComplet: 'Krypton',
            nombreAtomique: 36,
            masseAtomique: 83.80,
            rayonIonique: '--',
            rayonCovalent: 116,
            nombreDeMasse: 84,
            nombreDeNeutrons: 48,
            electronegativite: '--',
            energieIonisation: 1350.8,
            electronsValence: 8,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 16.78,
        },
        {
            nom: 'Rb',
            nomComplet: 'Rubidium',
            nombreAtomique: 37,
            masseAtomique: 85.4678,
            rayonIonique: 10.148,
            rayonCovalent: 220,
            nombreDeMasse: 85,
            nombreDeNeutrons: 48,
            electronegativite: 0.8,
            energieIonisation: 	403.0,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 319.8,
        },
        {
            nom: 'Sr',
            nomComplet: 'Strontium',
            nombreAtomique: 38,
            masseAtomique: 87.62,
            rayonIonique: 0.113,
            rayonCovalent: 195,
            nombreDeMasse: 88,
            nombreDeNeutrons: 50,
            electronegativite: 1.0,
            energieIonisation: 549.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 197.2,
        },
        {
            nom: 'Y',
            nomComplet: 'Yttrium',
            nombreAtomique: 39,
            masseAtomique: 88.9059,
            rayonIonique: 0.093,
            rayonCovalent: 190,
            nombreDeMasse: 89,
            nombreDeNeutrons: 50,
            electronegativite: 1.2,
            energieIonisation: 	600,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 162,
        },
        {
            nom: 'Zr',
            nomComplet: 'Zirconium',
            nombreAtomique: 40,
            masseAtomique: 91.22,
            rayonIonique: 0.079,
            rayonCovalent: 175,
            nombreDeMasse: 90,
            nombreDeNeutrons: 50,
            electronegativite: 1.3,
            energieIonisation: 640.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 112,
        },
        {
            nom: 'Nb',
            nomComplet: 'Niobium',
            nombreAtomique: 41,
            masseAtomique: 92.9064,
            rayonIonique: 0.070,
            rayonCovalent: 164,
            nombreDeMasse: 93,
            nombreDeNeutrons: 52,
            electronegativite: 1.6,
            energieIonisation: 652.1,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 98,
        },
        {
            nom: 'Mo',
            nomComplet: 'Molybdène',
            nombreAtomique: 42,
            masseAtomique: 95.94,
            rayonIonique: 0.062,
            rayonCovalent: 154,
            nombreDeMasse: 98,
            nombreDeNeutrons: 56,
            electronegativite: 2.2,
            energieIonisation: 684.3,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 87,
        },
        {
            nom: 'Tc',
            nomComplet: 'Technétium',
            nombreAtomique: 43,
            masseAtomique: 98,
            rayonIonique: 0.058,
            rayonCovalent: 147,
            nombreDeMasse: 97,
            nombreDeNeutrons: 54,
            electronegativite: 2.1,
            energieIonisation: 702,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 79,
        },
        {
            nom: 'Ru',
            nomComplet: 'Ruthénium',
            nombreAtomique: 44,
            masseAtomique: 	101.07,
            rayonIonique: 0.054,
            rayonCovalent: 146,
            nombreDeMasse: 102,
            nombreDeNeutrons: 58,
            electronegativite: 2.2,
            energieIonisation: 710.2,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 72,
        },
        {
            nom: 'Rh',
            nomComplet: 'Rhodium',
            nombreAtomique: 45,
            masseAtomique: 102.9055,
            rayonIonique: 0.067,
            rayonCovalent: 142,
            nombreDeMasse: 103,
            nombreDeNeutrons: 58,
            electronegativite: 2.3,
            energieIonisation: 719.7,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 66,
        },
        {
            nom: 'Pd',
            nomComplet: 'Palladium',
            nombreAtomique: 46,
            masseAtomique: 106.4,
            rayonIonique: 0.064,
            rayonCovalent: 139,
            nombreDeMasse: 106,
            nombreDeNeutrons: 60,
            electronegativite: 2.2,
            energieIonisation: 804.4,
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 26.14,
        },
        {
            nom: 'Ag',
            nomComplet: 'Argent',
            nombreAtomique: 47,
            masseAtomique: 	107.868,
            rayonIonique: 0.126,
            rayonCovalent: 145,
            nombreDeMasse: 107,
            nombreDeNeutrons: 60,
            electronegativite: 1.9,
            energieIonisation: 731.0,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 55,
        },
        {
            nom: 'Cd',
            nomComplet: 'Cadmium',
            nombreAtomique: 48,
            masseAtomique: 112.41,
            rayonIonique: 0.097,
            rayonCovalent: 144,
            nombreDeMasse: 114,
            nombreDeNeutrons: 66,
            electronegativite: 1.7,
            energieIonisation: 867.8,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 46,
        },
        {
            nom: 'In',
            nomComplet: 'Indium',
            nombreAtomique: 49,
            masseAtomique: 114.82,
            rayonIonique: 0.081,
            rayonCovalent: 142,
            nombreDeMasse: 115,
            nombreDeNeutrons: 66,
            electronegativite: 1.8,
            energieIonisation: 558.3,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 65,
        },
        {
            nom: 'Sn',
            nomComplet: 'Étain',
            nombreAtomique: 50,
            masseAtomique: 118.69,
            rayonIonique: 0.071,
            rayonCovalent: 139,
            nombreDeMasse: 120,
            nombreDeNeutrons: 70,
            electronegativite: 2.0,
            energieIonisation: 708.6,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 53,
        },
        {
            nom: 'Sb',
            nomComplet: 'Antimoine',
            nombreAtomique: 51,
            masseAtomique: 121.75,
            rayonIonique: 0.062,
            rayonCovalent: 139,
            nombreDeMasse: 121,
            nombreDeNeutrons: 70,
            electronegativite: 2.1,
            energieIonisation: 	834,
            electronsValence: 5,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 43,
        },
        {
            nom: 'Te',
            nomComplet: 'Tellure',
            nombreAtomique: 52,
            masseAtomique: 	127.60,
            rayonIonique: 0.221,
            rayonCovalent: 138,
            nombreDeMasse: 130,
            nombreDeNeutrons: 78,
            electronegativite: 2.1,
            energieIonisation: 869.3,
            electronsValence: 6,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 38,
        },
        {
            nom: 'I',
            nomComplet: 'Iode',
            nombreAtomique: 53,
            masseAtomique: 126.9045,
            rayonIonique: 0.216,
            rayonCovalent: 139,
            nombreDeMasse: 127,
            nombreDeNeutrons: 74,
            electronegativite: 2.7,
            energieIonisation: 1008.4,
            electronsValence: 7,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 32.9,
        },
        {
            nom: 'Xe',
            nomComplet: 'Xénon',
            nombreAtomique: 54,
            masseAtomique: 131.30,
            rayonIonique: '--',
            rayonCovalent: 140,
            nombreDeMasse: 132,
            nombreDeNeutrons: 78,
            electronegativite: 2.6,
            energieIonisation: 1170.4,
            electronsValence: 8,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 27.32,
        },
        {
            nom: 'Cs',
            nomComplet: 'Césium',
            nombreAtomique: 55,
            masseAtomique: 132.9054,
            rayonIonique: 0.169,
            rayonCovalent: 244,
            nombreDeMasse: 133,
            nombreDeNeutrons: 78,
            electronegativite: 0.8,
            energieIonisation: 375.7,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 400.9,
        },
        {
            nom: 'Ba',
            nomComplet: 'Baryum',
            nombreAtomique: 56,
            masseAtomique: 	137.33,
            rayonIonique: 0.135,
            rayonCovalent: 215,
            nombreDeMasse: 138,
            nombreDeNeutrons: 82,
            electronegativite: 0.9,
            energieIonisation: 502.9,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 272,
        },
        {
            nom: 'La',
            nomComplet: 'Lanthane',
            nombreAtomique: 57,
            masseAtomique: 	138.9055,
            rayonIonique: 0.106,
            rayonCovalent: '--',
            nombreDeMasse: 139,
            nombreDeNeutrons: 82,
            electronegativite: 1.1,
            energieIonisation: 538.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 215,
        },
        {
            nom: 'Ce',
            nomComplet: 'Cérium',
            nombreAtomique: 58,
            masseAtomique: 140.12,
            rayonIonique: 0.103,
            rayonCovalent: '--',
            nombreDeMasse: 140,
            nombreDeNeutrons: 82,
            electronegativite: '--',
            energieIonisation: 534.4,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 205,
        },
        {
            nom: 'Pr',
            nomComplet: 'Praséodyme',
            nombreAtomique: 59,
            masseAtomique: 140.9077,
            rayonIonique: 0.101,
            rayonCovalent: '--',
            nombreDeMasse: 141,
            nombreDeNeutrons: 82,
            electronegativite: '--',
            energieIonisation: 527,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 216,
        },
        {
            nom: 'Nd',
            nomComplet: 'Néodyme',
            nombreAtomique: 60,
            masseAtomique: 144.24,
            rayonIonique: 0.100,
            rayonCovalent: '--',
            nombreDeMasse: 142,
            nombreDeNeutrons: 82,
            electronegativite: '--',
            energieIonisation: 533.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 208,
        },
        {
            nom: 'Pm',
            nomComplet: 'Prométhium',
            nombreAtomique: 61,
            masseAtomique: 145,
            rayonIonique: 0.098,
            rayonCovalent: '--',
            nombreDeMasse: 145,
            nombreDeNeutrons: 84,
            electronegativite: '--',
            energieIonisation: 	540,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 200,
        },
        {
            nom: 'Sm',
            nomComplet: 'Samarium',
            nombreAtomique: 62,
            masseAtomique: 150.4,
            rayonIonique: 0.096,
            rayonCovalent: '--',
            nombreDeMasse: 152,
            nombreDeNeutrons: 90,
            electronegativite: '--',
            energieIonisation: 544.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 192,
        },
        {
            nom: 'Eu',
            nomComplet: 'Europium',
            nombreAtomique: 63,
            masseAtomique: 151.96,
            rayonIonique: 0.095,
            rayonCovalent: '--',
            nombreDeMasse: 153,
            nombreDeNeutrons: 90,
            electronegativite: '--',
            energieIonisation: 547.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 184,
        },
        {
            nom: 'Gd',
            nomComplet: 'Gadolinium',
            nombreAtomique: 64,
            masseAtomique: 157.25,
            rayonIonique: 0.094,
            rayonCovalent: '--',
            nombreDeMasse: 158,
            nombreDeNeutrons: 94,
            electronegativite: '--',
            energieIonisation: 593.4,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 158,
        },
        {
            nom: 'Tb',
            nomComplet: 'Terbium',
            nombreAtomique: 65,
            masseAtomique: 158.9254,
            rayonIonique: 0.092,
            rayonCovalent: '--',
            nombreDeMasse: 159,
            nombreDeNeutrons: 94,
            electronegativite: '--',
            energieIonisation: 565.8,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 170,
        },
        {
            nom: 'Dy',
            nomComplet: 'Dysprosium',
            nombreAtomique: 66,
            masseAtomique: 162.50,
            rayonIonique: 0.091,
            rayonCovalent: '--',
            nombreDeMasse: 164,
            nombreDeNeutrons: 98,
            electronegativite: '--',
            energieIonisation: 573.0,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 163,
        },
        {
            nom: 'Ho',
            nomComplet: 'Holmium',
            nombreAtomique: 67,
            masseAtomique: 164.9304,
            rayonIonique: 0.089,
            rayonCovalent: '--',
            nombreDeMasse: 165,
            nombreDeNeutrons: 98,
            electronegativite: '--',
            energieIonisation: 	581.0,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 156,
        },
        {
            nom: 'Er',
            nomComplet: 'Erbium',
            nombreAtomique: 68,
            masseAtomique: 167.26,
            rayonIonique: 0.088,
            rayonCovalent: '--',
            nombreDeMasse: 166,
            nombreDeNeutrons: 98,
            electronegativite: '--',
            energieIonisation: 589.3,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 150,
        },
        {
            nom: 'Tm',
            nomComplet: 'Thulium',
            nombreAtomique: 69,
            masseAtomique: 	168.9342,
            rayonIonique: 0.087,
            rayonCovalent: '--',
            nombreDeMasse: 169,
            nombreDeNeutrons: 100,
            electronegativite: '--',
            energieIonisation: 596.7,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 144,
        },
        {
            nom: 'Yb',
            nomComplet: 'Ytterbium',
            nombreAtomique: 70,
            masseAtomique: 173.04,
            rayonIonique: 0.086,
            rayonCovalent: '--',
            nombreDeMasse: 174,
            nombreDeNeutrons: 104,
            electronegativite: '--',
            energieIonisation: 603.4,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 139,
        },
        {
            nom: 'Lu',
            nomComplet: 'Lutécium',
            nombreAtomique: 71,
            masseAtomique: 174.967,
            rayonIonique: 0.085,
            rayonCovalent: 187,
            nombreDeMasse: 175,
            nombreDeNeutrons: 104,
            electronegativite: '--',
            energieIonisation: 523.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 137,
        },
        {
            nom: 'Hf',
            nomComplet: 'Hafnium',
            nombreAtomique: 72,
            masseAtomique: 178.49,
            rayonIonique: 0.078,
            rayonCovalent: 175,
            nombreDeMasse: 180,
            nombreDeNeutrons: 108,
            electronegativite: 1.3,
            energieIonisation: 658.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 103,
        },
        {
            nom: 'Ta',
            nomComplet: 'Tantale',
            nombreAtomique: 73,
            masseAtomique: 	180.9479,
            rayonIonique: 0.070,
            rayonCovalent: 170,
            nombreDeMasse: 181,
            nombreDeNeutrons: 108,
            electronegativite: 1.5,
            energieIonisation: 761,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 74,
        },
        {
            nom: 'W',
            nomComplet: 'Tungstène',
            nombreAtomique: 74,
            masseAtomique: 183.85,
            rayonIonique: 0.065,
            rayonCovalent: 162,
            nombreDeMasse: 184,
            nombreDeNeutrons: 110,
            electronegativite: 1.7,
            energieIonisation: 	770,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 68,
        },
        {
            nom: 'Re',
            nomComplet: 'Rhénium',
            nombreAtomique: 75,
            masseAtomique: 	186.207,
            rayonIonique: 0.060,
            rayonCovalent: 151,
            nombreDeMasse: 187,
            nombreDeNeutrons: 112,
            electronegativite: 1.9,
            energieIonisation: 760,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 62,
        },
        {
            nom: 'Os',
            nomComplet: 'Osmium',
            nombreAtomique: 76,
            masseAtomique: 	190.2,
            rayonIonique: 0.053,
            rayonCovalent: 144,
            nombreDeMasse: 192,
            nombreDeNeutrons: 116,
            electronegativite: 2.2,
            energieIonisation: 840,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 57,
        },
        {
            nom: 'Ir',
            nomComplet: 'Iridium',
            nombreAtomique: 77,
            masseAtomique: 192.22,
            rayonIonique: 0.064,
            rayonCovalent: 141,
            nombreDeMasse: 193,
            nombreDeNeutrons: 116,
            electronegativite: 2.2,
            energieIonisation: 880,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 54,
        },
        {
            nom: 'Pt',
            nomComplet: 'Platine',
            nombreAtomique: 78,
            masseAtomique: 	195.09,
            rayonIonique: 0.070,
            rayonCovalent: 136,
            nombreDeMasse: 195,
            nombreDeNeutrons: 117,
            electronegativite: 2.2,
            energieIonisation: 870,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 48,
        },
        {
            nom: 'Au',
            nomComplet: 'Or',
            nombreAtomique: 79,
            masseAtomique: 196.9665,
            rayonIonique: 0.137,
            rayonCovalent: 136,
            nombreDeMasse: 197,
            nombreDeNeutrons: 118,
            electronegativite: 2.4,
            energieIonisation: 890.1,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 36,
        },
        {
            nom: 'Hg',
            nomComplet: 'Mercure',
            nombreAtomique: 80,
            masseAtomique: 	200.59,
            rayonIonique: 0.110,
            rayonCovalent: '--',
            nombreDeMasse: 202,
            nombreDeNeutrons: 122,
            electronegativite: 1.9,
            energieIonisation: 1007.1,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 33.91,
        },
        {
            nom: 'Tl',
            nomComplet: 'Thallium',
            nombreAtomique: 81,
            masseAtomique: 204.37,
            rayonIonique: 0.095,
            rayonCovalent: 145,
            nombreDeMasse: 205,
            nombreDeNeutrons: 124,
            electronegativite: 2.0,
            energieIonisation: 589.4,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 50,
        },
        {
            nom: 'Pb',
            nomComplet: 'Plomb',
            nombreAtomique: 82,
            masseAtomique: 207.2,
            rayonIonique: 0.084,
            rayonCovalent: 146,
            nombreDeMasse: 208,
            nombreDeNeutrons: 126,
            electronegativite: 2.3,
            energieIonisation: 715.6,
            electronsValence: 4,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 47,
        },
        {
            nom: 'Bi',
            nomComplet: 'Bismuth',
            nombreAtomique: 83,
            masseAtomique: 	208.9804,
            rayonIonique: 0.074,
            rayonCovalent: 148,
            nombreDeMasse: 209,
            nombreDeNeutrons: 126,
            electronegativite: 2.0,
            energieIonisation: 703,
            electronsValence: 5,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 48,
        },
        {
            nom: 'Po',
            nomComplet: 'Polonium',
            nombreAtomique: 84,
            masseAtomique: 209,
            rayonIonique: 0.056,
            rayonCovalent: 140,
            nombreDeMasse: 209,
            nombreDeNeutrons: 125,
            electronegativite: 2.0,
            energieIonisation: 812.1,
            electronsValence: 6,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 44,
        },
        {
            nom: 'At',
            nomComplet: 'Astate',
            nombreAtomique: 85,
            masseAtomique: 210,
            rayonIonique: 0.227,
            rayonCovalent: 150,
            nombreDeMasse: 210,
            nombreDeNeutrons: 125,
            electronegativite: 2.2,
            energieIonisation: 899.003,
            electronsValence: 7,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 42,
        },
        {
            nom: 'Rn',
            nomComplet: 'Radon',
            nombreAtomique: 86,
            masseAtomique: 222,
            rayonIonique: '--',
            rayonCovalent: 150,
            nombreDeMasse: 222,
            nombreDeNeutrons: 136,
            electronegativite: '--',
            energieIonisation: 1037,
            electronsValence: 8,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 35,
        },
        {
            nom: 'Fr',
            nomComplet: 'Francium',
            nombreAtomique: 87,
            masseAtomique: 223,
            rayonIonique: 0.176,
            rayonCovalent: 260,
            nombreDeMasse: 223,
            nombreDeNeutrons: 136,
            electronegativite: 0.7,
            energieIonisation: 380,
            electronsValence: 1,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 317.8,
        },
        {
            nom: 'Ra',
            nomComplet: 'Radium',
            nombreAtomique: 88,
            masseAtomique: 226.0254,
            rayonIonique: 0.140,
            rayonCovalent: 221,
            nombreDeMasse: 226,
            nombreDeNeutrons: 138,
            electronegativite: 0.9,
            energieIonisation: 509.3,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 246,
        },
        {
            nom: 'Ac',
            nomComplet: 'Actinium',
            nombreAtomique: 89,
            masseAtomique: 	227.0278,
            rayonIonique: 0.111,
            rayonCovalent: '--',
            nombreDeMasse: 227,
            nombreDeNeutrons: 138,
            electronegativite: 1.1,
            energieIonisation: 499,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 203,
        },
        {
            nom: 'Th',
            nomComplet: 'Thorium',
            nombreAtomique: 90,
            masseAtomique: 	232.0381,
            rayonIonique: 0.108,
            rayonCovalent: '--',
            nombreDeMasse: 232,
            nombreDeNeutrons: 142,
            electronegativite: '--',
            energieIonisation: 587,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 217,
        },
        {
            nom: 'Pa',
            nomComplet: 'Protactinium',
            nombreAtomique: 91,
            masseAtomique: 231.0359,
            rayonIonique: 0.105,
            rayonCovalent: '--',
            nombreDeMasse: 231,
            nombreDeNeutrons: 140,
            electronegativite: '--',
            energieIonisation: 568,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 154,
        },
        {
            nom: 'U',
            nomComplet: 'Uranium',
            nombreAtomique: 92,
            masseAtomique: 	238.029,
            rayonIonique: 0.103,
            rayonCovalent: '--',
            nombreDeMasse: 238,
            nombreDeNeutrons:146 ,
            electronegativite: '--',
            energieIonisation: 597.6,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 129,
        },
        {
            nom: 'Np',
            nomComplet: 'Neptunium',
            nombreAtomique: 93,
            masseAtomique: 237.0482,
            rayonIonique: 0.101,
            rayonCovalent: '--',
            nombreDeMasse: 237,
            nombreDeNeutrons: 144,
            electronegativite: '--',
            energieIonisation: 604.5,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 151,
        },
        {
            nom: 'Pu',
            nomComplet: 'Plutonium',
            nombreAtomique: 94,
            masseAtomique: 242,
            rayonIonique: 0.100,
            rayonCovalent: '--',
            nombreDeMasse: 244,
            nombreDeNeutrons: 150,
            electronegativite: '--',
            energieIonisation: 584.7,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 132,
        },
        {
            nom: 'Am',
            nomComplet: 'Américium',
            nombreAtomique: 95,
            masseAtomique: 243,
            rayonIonique: 0.099,
            rayonCovalent: '--',
            nombreDeMasse: 243,
            nombreDeNeutrons: 148,
            electronegativite: '--',
            energieIonisation: 578,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 131,
        },
        {
            nom: 'Cm',
            nomComplet: 'Curium',
            nombreAtomique: 96,
            masseAtomique: 247,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 247,
            nombreDeNeutrons: 151,
            electronegativite: '--',
            energieIonisation: 581,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 144,
        },
        {
            nom: 'Bk',
            nomComplet: 'Berkélium',
            nombreAtomique: 97,
            masseAtomique: 247,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 247,
            nombreDeNeutrons: 150,
            electronegativite: '--',
            energieIonisation: 601,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 125,
        },
        {
            nom: 'Cf',
            nomComplet: 'Californium',
            nombreAtomique: 98,
            masseAtomique: 251,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 251,
            nombreDeNeutrons: 153,
            electronegativite: '--',
            energieIonisation: 	608,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 122,
        },
        {
            nom: 'Es',
            nomComplet: 'Einsteinium',
            nombreAtomique: 99,
            masseAtomique: 252,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 252,
            nombreDeNeutrons: 153,
            electronegativite: '--',
            energieIonisation: 619,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 118,
        },
        {
            nom: 'Fm',
            nomComplet: 'Fermium',
            nombreAtomique: 100,
            masseAtomique: 257,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 257,
            nombreDeNeutrons: 157,
            electronegativite: '--',
            energieIonisation: 627,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 113,
        },
        {
            nom: 'Md',
            nomComplet: 'Mendélévium',
            nombreAtomique: 101,
            masseAtomique: 258,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 258,
            nombreDeNeutrons: 157,
            electronegativite: '--',
            energieIonisation: 	635,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 109,
        },
        {
            nom: 'No',
            nomComplet: 'Nobélium',
            nombreAtomique: 102,
            masseAtomique: 250,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 259,
            nombreDeNeutrons: 157,
            electronegativite: '--',
            energieIonisation: 	642,
            electronsValence: 2,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 110,
        },
        {
            nom: 'Lr',
            nomComplet: 'Lawrencium',
            nombreAtomique: 103,
            masseAtomique: 260,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 266,
            nombreDeNeutrons: 163,
            electronegativite: '--',
            energieIonisation: 470,
            electronsValence: 3,
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 320,
        },
        {
            nom: 'Rf',
            nomComplet: 'Rutherfordium',
            nombreAtomique: 104,
            masseAtomique: 261,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 267,
            nombreDeNeutrons: 163,
            electronegativite: '--',
            energieIonisation: 	580,
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 112,
        },
        {
            nom: 'Db',
            nomComplet: 'Dubnium',
            nombreAtomique: 105,
            masseAtomique: 262,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 268,
            nombreDeNeutrons: 163,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 42,
        },
        {
            nom: 'Sg',
            nomComplet: 'Seaborgium',
            nombreAtomique: 106,
            masseAtomique: 263,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 269,
            nombreDeNeutrons: 163,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 40,
        },
        {
            nom: 'Bh',
            nomComplet: 'Bohrium',
            nombreAtomique: 107,
            masseAtomique: 262,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 270,
            nombreDeNeutrons: 163,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 38,
        },
        {
            nom: 'Hs',
            nomComplet: 'Hassium',
            nombreAtomique: 108,
            masseAtomique: 255,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 269,
            nombreDeNeutrons: 161,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 36,
        },
        {
            nom: 'Mt',
            nomComplet: 'Meitnérium',
            nombreAtomique: 109,
            masseAtomique: 256,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 278,
            nombreDeNeutrons: 169,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 34,
        },
        {
            nom: 'Ds',
            nomComplet: 'Darmstadtium',
            nombreAtomique: 110,
            masseAtomique: 269,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 281,
            nombreDeNeutrons: 171,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 32,
        },
        {
            nom: 'Rg',
            nomComplet: 'Roentgenium',
            nombreAtomique: 111,
            masseAtomique: 272,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 282,
            nombreDeNeutrons: 171,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 32,
        },
        {
            nom: 'uub',
            nomComplet: 'Ununbium',
            nombreAtomique: 112,
            masseAtomique: 277,
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 285,
            nombreDeNeutrons: 173,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 28,
        },
        {
            nom: 'Uut',
            nomComplet: 'Ununtrium',
            nombreAtomique: 113,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 286,
            nombreDeNeutrons: 173,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 29,
        },
        {
            nom: 'Uuq',
            nomComplet: 'Ununquadium',
            nombreAtomique: 114,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 289,
            nombreDeNeutrons: 175,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 31,
        },
        {
            nom: 'Uup',
            nomComplet: 'Ununpentium',
            nombreAtomique: 115,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 290,
            nombreDeNeutrons: 175,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 71,
        },
        {
            nom: 'Uuh',
            nomComplet: 'Ununhexium',
            nombreAtomique: 116,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 293,
            nombreDeNeutrons: 177,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* '--',
        },
        {
            nom: 'Uus',
            nomComplet: 'Ununseptium',
            nombreAtomique: 117,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 294,
            nombreDeNeutrons: 177,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 76,
        },
        {
            nom: 'Uuo',
            nomComplet: 'Ununoctium',
            nombreAtomique: 118,
            masseAtomique: '--',
            rayonIonique: '--',
            rayonCovalent: '--',
            nombreDeMasse: 294,
            nombreDeNeutrons: 176,
            electronegativite: '--',
            energieIonisation: '--',
            electronsValence: '--',
            polarisabilite: 1.4838996*Math.pow(10,-31)*Math.pow(10,30)* 58,
        },
    ],
    AtomsDataPerso: [],
};

const getters= {
    getAtomsData: (state)=>state.AtomsData,
    getAtomsDataPerso: (state)=>state.AtomsDataPerso,
};
const mutations= {
    addAtomData(state, payload) {
        state.AtomsDataPerso.push(payload);
    }
}

export default {
    state,
    getters,
    mutations,
}